import { describe, it, expect, vi, beforeEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import type { BearerTokens, StatePersistence } from '@chrischall/mcp-utils/session';
import { resolveAuth } from '../src/auth.js';
import { makeGetClient } from '../src/get-client.js';
import { registerHealthcheckTools } from '../src/tools/health.js';

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * These drive the REAL auth + client stack (fetch stubbed) against the page
 * CloudFront serves, on each hop that can meet it: the API probe itself, the
 * refresh grant, and the login page. The refresh case also pins the expensive
 * failure: a blocked refresh must not be read as a revoked refresh token,
 * because TokenManager answers that by CLEARING the token cache — and Skylight
 * rotates refresh tokens, so the cached one is the only live copy.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return {
    ok: false,
    status: 403,
    statusText: 'Forbidden',
    headers: new Headers({
      'content-type': 'text/html',
      'x-cache': 'Error from cloudfront',
      server: 'CloudFront',
    }),
    text: async () => CLOUDFRONT_BLOCK,
  } as unknown as Response;
}

function json(body: unknown, status = 200): Response {
  return {
    ok: status >= 200 && status < 300,
    status,
    statusText: 'OK',
    headers: new Headers({ 'content-type': 'application/json' }),
    text: async () => JSON.stringify(body),
    json: async () => body,
    clone() {
      return this;
    },
  } as unknown as Response;
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

function memoryStore(tokens: BearerTokens | null) {
  let held = tokens;
  const clear = vi.fn(() => {
    held = null;
  });
  const store: StatePersistence<BearerTokens> = {
    load: () => held,
    save: (t: BearerTokens) => {
      held = t;
    },
    clear,
  };
  return { store, clear };
}

async function healthcheck(
  httpFetch: (url: string, init?: RequestInit) => Promise<Response>,
  persistence: StatePersistence<BearerTokens> | null,
): Promise<Result> {
  const getClient = makeGetClient(() => resolveAuth({ httpFetch, persistence }));
  const h = await createTestHarness((server) => registerHealthcheckTools(server, getClient));
  const res = await h.client.callTool({ name: 'skylight_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

beforeEach(() => {
  for (const k of Object.keys(process.env)) if (k.startsWith('SKYLIGHT_')) delete process.env[k];
});

describe('a CloudFront block reads as edge_blocked, not a rejected credential', () => {
  it('on the API probe, with a cached token', async () => {
    process.env.SKYLIGHT_REFRESH_TOKEN = 'ENV_RT';
    const { store } = memoryStore({ accessToken: 'AT', refreshToken: 'RT', expiresAt: Date.now() + 3_600_000 });
    const httpFetch = vi.fn(async (_url: string, _init?: RequestInit) => blocked());

    const r = await healthcheck(httpFetch, store);

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('on the refresh grant — and the cached refresh token survives it', async () => {
    process.env.SKYLIGHT_REFRESH_TOKEN = 'ENV_RT';
    // Expired access token, so the probe has to refresh first.
    const { store, clear } = memoryStore({ accessToken: 'AT', refreshToken: 'ROTATED_RT', expiresAt: Date.now() - 1000 });
    const httpFetch = vi.fn(async (_url: string, _init?: RequestInit) => blocked());

    const r = await healthcheck(httpFetch, store);

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/Verify SKYLIGHT_EMAIL/);
    // Nothing judged the refresh token, so nothing may throw it away.
    expect(clear).not.toHaveBeenCalled();
    expect(store.load()).toMatchObject({ refreshToken: 'ROTATED_RT' });
  });

  it('on a cold start from SKYLIGHT_REFRESH_TOKEN — not "rejected the supplied refresh token"', async () => {
    process.env.SKYLIGHT_REFRESH_TOKEN = 'ENV_RT';
    process.env.SKYLIGHT_EMAIL = 'a@b.com';
    process.env.SKYLIGHT_PASSWORD = 'pw';
    const httpFetch = vi.fn(async (_url: string, _init?: RequestInit) => blocked());

    const r = await healthcheck(httpFetch, null);

    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.message).not.toMatch(/rejected the supplied refresh token/);
    // The login sits behind the same edge; a rate-limited attempt is not spent on it.
    expect(httpFetch.mock.calls.map((c) => String(c[0]))).not.toContainEqual(
      expect.stringContaining('/auth/session'),
    );
  });

  it('on the login page', async () => {
    process.env.SKYLIGHT_EMAIL = 'a@b.com';
    process.env.SKYLIGHT_PASSWORD = 'pw';
    const httpFetch = vi.fn(async (_url: string, _init?: RequestInit) => blocked());

    const r = await healthcheck(httpFetch, null);

    expect(r.ok).toBe(false);
    // Was `login_page_changed`: the block page has no CSRF token either.
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('control: a refresh the token endpoint rejects is still not an edge block', async () => {
    process.env.SKYLIGHT_REFRESH_TOKEN = 'ENV_RT';
    const { store } = memoryStore({ accessToken: 'AT', refreshToken: 'RT', expiresAt: Date.now() - 1000 });
    const httpFetch = vi.fn(async () => json({ error: 'invalid_grant' }, 400));

    const r = await healthcheck(httpFetch, store);

    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });

  it('control: a refusal whose body cannot be read is judged on what is left', async () => {
    process.env.SKYLIGHT_REFRESH_TOKEN = 'ENV_RT';
    const { store } = memoryStore({ accessToken: 'AT', refreshToken: 'RT', expiresAt: Date.now() - 1000 });
    const unreadable = {
      ok: false,
      status: 403,
      statusText: 'Forbidden',
      headers: new Headers({ 'content-type': 'text/html' }),
      text: async () => {
        throw new Error('body stream already read');
      },
    } as unknown as Response;
    const httpFetch = vi.fn(async () => unreadable);

    const r = await healthcheck(httpFetch, store);

    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });
});

describe('a CloudFront block on the login POSTs reads as edge_blocked', () => {
  const loginPage = (): Response =>
    ({
      ok: true,
      status: 200,
      statusText: 'OK',
      headers: new Headers({ 'content-type': 'text/html', 'set-cookie': '_skylight_cloud_session=abc; Path=/' }),
      text: async () => '<input type="hidden" name="authenticity_token" value="CSRF">',
    }) as unknown as Response;
  const redirect = (location: string): Response =>
    ({
      ok: false,
      status: 302,
      statusText: 'Found',
      headers: new Headers({ location }),
      text: async () => '',
    }) as unknown as Response;

  /** The live four-step login, with `blockedStep` answered by CloudFront. */
  function loginFetch(blockedStep: 'session' | 'token') {
    return vi.fn(async (url: string, init?: RequestInit) => {
      const { pathname } = new URL(url);
      if (pathname === '/auth/session/new') return loginPage();
      if (pathname === '/auth/session' && init?.method === 'POST') {
        return blockedStep === 'session' ? blocked() : redirect('https://app.ourskylight.com/auth/session/success');
      }
      if (pathname === '/oauth/authorize') return redirect('https://ourskylight.com/welcome?code=CODE');
      if (pathname === '/oauth/token') return blockedStep === 'token' ? blocked() : json({ access_token: 'AT' });
      return json({ data: [] });
    });
  }

  for (const [step, path] of [
    ['session', '/auth/session'],
    ['token', '/oauth/token'],
  ] as const) {
    it(step === 'session' ? 'on step 2 (POST /auth/session)' : 'on step 4 (POST /oauth/token code exchange)', async () => {
      process.env.SKYLIGHT_EMAIL = 'a@b.com';
      process.env.SKYLIGHT_PASSWORD = 'pw';
      const { store, clear } = memoryStore(null);
      const httpFetch = loginFetch(step);

      const r = await healthcheck(httpFetch, store);

      expect(r.ok).toBe(false);
      expect(r.error?.kind).toBe('edge_blocked');
      expect(r.error?.message).toContain(`POST ${path}`);
      // Not the credential's fault, so not advice to change it or wait out a rate limit.
      expect(r.hint).not.toMatch(/Verify SKYLIGHT_EMAIL|rate-limit/);
      // Nothing was minted, and nothing stored was judged or thrown away.
      expect(clear).not.toHaveBeenCalled();
      expect(store.load()).toBeNull();
      // The login stops at the blocked hop: no further attempts are spent behind the same edge.
      const calls = httpFetch.mock.calls.map((c) => new URL(String(c[0])).pathname);
      expect(calls.filter((p) => p === path)).toHaveLength(1);
      expect(calls.at(-1)).toBe(path);
    });
  }
});
